<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>src</string>
	</array>
	<key>name</key>
	<string>Cartfile</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#dependency</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(?=#)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.cartfile</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>#</string>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.number-sign.cartfile</string>
				</dict>
			</array>
		</dict>
		<key>dependency</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(git|github)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.dependency.origin</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\n|(?=#))</string>
					<key>name</key>
					<string>source.cartfile.dependency</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#version</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#repository</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>repository</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=(?:git\s|github\s))"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.cartfile.repository</string>
		</dict>
		<key>version</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.version-requirement</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.tag</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(&gt;=|~&gt;|==)\s+([\w\.]+)</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;!(?:git\s|github\s))"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.cartfile.revision</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.cartfile</string>
	<key>uuid</key>
	<string>6ACB6D10-085F-4ACC-8235-06CB6F2DCBA4</string>
</dict>
</plist>
